version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/src/
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app/